"""配置表数据库表结构的权威定义。

在此文件中定义 cfg_* 表的字段元数据；运行时使用这份静态表结构，
不从配置文件读取字段元数据。
"""
from __future__ import annotations

from copy import deepcopy
from typing import Any


# schema 来源元信息：标识当前表结构由 Python 静态定义维护，是运行时权威来源。
CONFIG_SCHEMA_SOURCE: dict[str, Any] = {
    'mode': 'python_static_schema',
    'authoritative': True,
    'note': (
        'Config table database schemas are fixed in Python; runtime does not read '
        'config_table_import_mapping.yaml for field metadata.'
    ),
}
# schema 生效范围：只导入和检查已映射的 Sheet 与字段，未映射内容按策略忽略。
CONFIG_SCOPE: dict[str, Any] = {
    'only_import_mapped_sheets': True,
    'only_import_mapped_fields': True,
    'only_check_mapped_sheets': True,
    'only_check_mapped_fields': True,
    'ignore_unmapped_sheets': True,
    'ignore_unmapped_fields': True,
    'missing_mapped_field_blocks': True,
}
# 系统字段策略：入库时统一追加配置名和写库时间等审计字段。
SYSTEM_FIELD_POLICY: dict[str, Any] = {
    'append_system_fields': True,
    'fields': [
        'config_name',
        'db_write_time',
    ],
}
# 配置表 schema 主定义：key 为配置表 Sheet 标识，value 为字段、主键、入库表等元数据。
CONFIG_TABLE_SCHEMAS: dict[str, dict[str, Any]] = {
    'Global_seed': {
        'local_sheet': 'Global_seed',
        'data_source': 'Excel sheet',
        'source_file': None,
        'db_table': 'cfg_global_seed',
        'import_enabled': True,
        'primary_key': [],
        'fields': [
            {
                'local_name': 'seed',
                'db_name': 'seed',
                'local_order': 1,
                'db_order': 1,
                'pandas_type': 'float64',
                'db_type': 'bigint',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': '全局随机种子',
                'comment_source': 'manual_mapping_completion',
                'db_field_exists': '是',
            },
        ],
        'system_fields': [
            {
                'db_name': 'config_name',
                'db_order': 9,
                'db_type': 'str',
                'comment': '配置名',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
            {
                'db_name': 'db_write_time',
                'db_order': 11,
                'db_type': 'timestamp without time zone',
                'comment': '写库时间',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
        ],
    },
    'Global_Network': {
        'local_sheet': 'Global_Network',
        'data_source': None,
        'source_file': None,
        'db_table': 'cfg_global_network',
        'import_enabled': True,
        'primary_key': [
            'material',
            'location',
            'sourcing',
            'eff_from',
            'eff_to',
        ],
        'fields': [
            {
                'local_name': 'material',
                'db_name': 'material',
                'local_order': 1,
                'db_order': 1,
                'pandas_type': 'int64',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': 'M',
                'comment': '物料号',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'location',
                'db_name': 'location',
                'local_order': 2,
                'db_order': 2,
                'pandas_type': 'str',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': 'S',
                'comment': '发货点',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'sourcing',
                'db_name': 'sourcing',
                'local_order': 3,
                'db_order': 3,
                'pandas_type': 'str',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': 'L',
                'comment': '收货点',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'location_type',
                'db_name': 'location_type',
                'local_order': 4,
                'db_order': 4,
                'pandas_type': 'str',
                'db_type': 'str',
                'primary_key': False,
                'notnull': True,
                'default': 'DC',
                'comment': '收货点类型',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'eff_from',
                'db_name': 'eff_from',
                'date_flag': 'start',
                'local_order': 5,
                'db_order': 5,
                'pandas_type': 'datetime64[us]',
                'db_type': 'timestamp without time zone',
                'primary_key': True,
                'notnull': True,
                'default': '1970-01-01',
                'comment': '生效时间',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'eff_to',
                'db_name': 'eff_to',
                'date_flag': 'end',
                'local_order': 6,
                'db_order': 6,
                'pandas_type': 'datetime64[us]',
                'db_type': 'timestamp without time zone',
                'primary_key': True,
                'notnull': True,
                'default': '9999-12-31',
                'comment': '失效时间',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
        ],
        'system_fields': [
            {
                'db_name': 'config_name',
                'db_order': 9,
                'db_type': 'str',
                'comment': '配置名',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
            {
                'db_name': 'db_write_time',
                'db_order': 11,
                'db_type': 'timestamp without time zone',
                'comment': '写库时间',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
        ],
    },
    'Global_SpaceCapacity': {
        'local_sheet': 'Global_SpaceCapacity',
        'data_source': None,
        'source_file': None,
        'db_table': 'cfg_global_spacecapacity',
        'import_enabled': True,
        'primary_key': [
            'location',
            'eff_from',
            'eff_to',
        ],
        'fields': [
            {
                'local_name': 'location',
                'db_name': 'location',
                'local_order': 1,
                'db_order': 1,
                'pandas_type': 'str',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': 'L',
                'comment': '地点',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'eff_from',
                'db_name': 'eff_from',
                'date_flag': 'start',
                'local_order': 2,
                'db_order': 2,
                'pandas_type': 'object',
                'db_type': 'timestamp without time zone',
                'primary_key': True,
                'notnull': True,
                'default': '1970-01-01T00:00:00',
                'comment': '生效时间',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'eff_to',
                'db_name': 'eff_to',
                'date_flag': 'end',
                'local_order': 3,
                'db_order': 3,
                'pandas_type': 'object',
                'db_type': 'timestamp without time zone',
                'primary_key': True,
                'notnull': True,
                'default': '9999-12-31T00:00:00',
                'comment': '失效时间',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'capacity',
                'db_name': 'capacity',
                'range': (0, None),
                'local_order': 4,
                'db_order': 4,
                'pandas_type': 'object',
                'db_type': 'double precision',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': '仓容',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
        ],
        'system_fields': [
            {
                'db_name': 'config_name',
                'db_order': 5,
                'db_type': 'str',
                'comment': '配置名',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
            {
                'db_name': 'db_write_time',
                'db_order': 7,
                'db_type': 'timestamp without time zone',
                'comment': '写库时间',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
        ],
    },
    'Global_LeadTime': {
        'local_sheet': 'Global_LeadTime',
        'data_source': None,
        'source_file': None,
        'db_table': 'cfg_global_leadtime',
        'import_enabled': True,
        'primary_key': [
            'sending',
            'receiving',
        ],
        'fields': [
            {
                'local_name': 'sending',
                'db_name': 'sending',
                'local_order': 1,
                'db_order': 1,
                'pandas_type': 'str',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '发货点',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'receiving',
                'db_name': 'receiving',
                'local_order': 2,
                'db_order': 2,
                'pandas_type': 'str',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '收货点',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'PDT',
                'db_name': 'pdt',
                'range': (0, None),
                'local_order': 3,
                'db_order': 3,
                'pandas_type': 'int64',
                'db_type': 'bigint',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': '计划交付时长',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'GR',
                'db_name': 'gr',
                'range': (0, None),
                'local_order': 4,
                'db_order': 4,
                'pandas_type': 'int64',
                'db_type': 'bigint',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': '收货时长',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'MCT',
                'db_name': 'mct',
                'range': (0, None),
                'local_order': 5,
                'db_order': 5,
                'pandas_type': 'int64',
                'db_type': 'bigint',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': '微检时间',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'OTD',
                'db_name': 'otd',
                'range': (0, None),
                'local_order': 6,
                'db_order': 6,
                'pandas_type': 'int64',
                'db_type': 'bigint',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': '运输时间',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
        ],
        'system_fields': [
            {
                'db_name': 'config_name',
                'db_order': 10,
                'db_type': 'str',
                'comment': '配置名',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
            {
                'db_name': 'db_write_time',
                'db_order': 12,
                'db_type': 'timestamp without time zone',
                'comment': '写库时间',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
        ],
    },
    'Global_DemandPriority': {
        'local_sheet': 'Global_DemandPriority',
        'data_source': None,
        'source_file': None,
        'db_table': 'cfg_global_demandpriority',
        'import_enabled': True,
        'primary_key': [
            'demand_element',
        ],
        'fields': [
            {
                'local_name': 'demand_element',
                'db_name': 'demand_element',
                'local_order': 1,
                'db_order': 1,
                'pandas_type': 'str',
                'db_type': 'text',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '需求类型优先级',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'priority',
                'db_name': 'priority',
                'range': (0, None),
                'local_order': 2,
                'db_order': 2,
                'pandas_type': 'int64',
                'db_type': 'bigint',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': '需求类型优先级',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
        ],
        'system_fields': [
            {
                'db_name': 'config_name',
                'db_order': 3,
                'db_type': 'text',
                'comment': '配置名',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
            {
                'db_name': 'db_write_time',
                'db_order': 5,
                'db_type': 'timestamp without time zone',
                'comment': '写库时间',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
        ],
    },
    'M1_InitialInventory': {
        'local_sheet': 'M1_InitialInventory',
        'data_source': None,
        'source_file': None,
        'db_table': 'cfg_m1_initialinventory',
        'import_enabled': True,
        'primary_key': [
            'material',
            'location',
        ],
        'fields': [
            {
                'local_name': 'material',
                'db_name': 'material',
                'local_order': 1,
                'db_order': 1,
                'pandas_type': 'int64',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '物料号',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'location',
                'db_name': 'location',
                'local_order': 2,
                'db_order': 2,
                'pandas_type': 'str',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '地点',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'quantity',
                'db_name': 'quantity',
                'range': (0, None),
                'local_order': 3,
                'db_order': 3,
                'pandas_type': 'int64',
                'db_type': 'double precision',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': '初始库存数量',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
        ],
        'system_fields': [
            {
                'db_name': 'config_name',
                'db_order': 4,
                'db_type': 'str',
                'comment': '配置名',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
            {
                'db_name': 'db_write_time',
                'db_order': 6,
                'db_type': 'timestamp without time zone',
                'comment': '写库时间',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
        ],
    },
    'M1_DemandForecast': {
        'local_sheet': 'M1_DemandForecast',
        'data_source': None,
        'source_file': None,
        'db_table': 'cfg_m1_demandforecast',
        'import_enabled': True,
        'primary_key': [
            'week',
            'material',
            'location',
        ],
        'fields': [
            {
                'local_name': 'week',
                'db_name': 'week',
                'local_order': 1,
                'db_order': 1,
                'pandas_type': 'int64',
                'db_type': 'bigint',
                'primary_key': True,
                'notnull': True,
                'default': 0,
                'comment': '需求周',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'material',
                'db_name': 'material',
                'local_order': 2,
                'db_order': 2,
                'pandas_type': 'int64',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': 'M',
                'comment': '物料号',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'location',
                'db_name': 'location',
                'local_order': 3,
                'db_order': 3,
                'pandas_type': 'str',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': 'L',
                'comment': '地点',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'quantity',
                'db_name': 'quantity',
                'range': (0, None),
                'local_order': 4,
                'db_order': 4,
                'pandas_type': 'float64',
                'db_type': 'double precision',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': '需求数量',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
        ],
        'system_fields': [
            {
                'db_name': 'config_name',
                'db_order': 5,
                'db_type': 'str',
                'comment': '配置名',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
            {
                'db_name': 'db_write_time',
                'db_order': 7,
                'db_type': 'timestamp without time zone',
                'comment': '写库时间',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
        ],
    },
    'M1_ForecastError': {
        'local_sheet': 'M1_ForecastError',
        'data_source': None,
        'source_file': None,
        'db_table': 'cfg_m1_forecasterror',
        'import_enabled': True,
        'primary_key': [
            'material',
            'location',
            'order_type',
        ],
        'fields': [
            {
                'local_name': 'material',
                'db_name': 'material',
                'local_order': 1,
                'db_order': 1,
                'pandas_type': 'int64',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '物料',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'location',
                'db_name': 'location',
                'local_order': 2,
                'db_order': 2,
                'pandas_type': 'str',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '地点',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'order_type',
                'db_name': 'order_type',
                'local_order': 3,
                'db_order': 3,
                'pandas_type': 'str',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '订单类型',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'error_std_percent',
                'db_name': 'error_std_percent',
                'range': (0, None),
                'local_order': 4,
                'db_order': 4,
                'pandas_type': 'float64',
                'db_type': 'double precision',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': '误差比例',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
        ],
        'system_fields': [
            {
                'db_name': 'config_name',
                'db_order': 5,
                'db_type': 'str',
                'comment': '配置名',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
            {
                'db_name': 'db_write_time',
                'db_order': 7,
                'db_type': 'timestamp without time zone',
                'comment': '写库时间',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
        ],
    },
    'M1_OrderCalendar': {
        'local_sheet': 'M1_OrderCalendar',
        'data_source': None,
        'source_file': None,
        'db_table': 'cfg_m1_ordercalendar',
        'import_enabled': True,
        'primary_key': [
            'date',
        ],
        'fields': [
            {
                'local_name': 'date',
                'db_name': 'date',
                'local_order': 1,
                'db_order': 1,
                'pandas_type': 'datetime64[us]',
                'db_type': 'timestamp without time zone',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '订单日',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'order_day_flag',
                'db_name': 'order_day_flag',
                'local_order': 2,
                'db_order': 2,
                'pandas_type': 'int64',
                'db_type': 'bool',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': '是否',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
        ],
        'system_fields': [
            {
                'db_name': 'config_name',
                'db_order': 3,
                'db_type': 'str',
                'comment': '配置名',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
            {
                'db_name': 'db_write_time',
                'db_order': 5,
                'db_type': 'timestamp without time zone',
                'comment': '写库时间',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
        ],
    },
    'M1_AOConfig': {
        'local_sheet': 'M1_AOConfig',
        'data_source': None,
        'source_file': None,
        'db_table': 'cfg_m1_aoconfig',
        'import_enabled': True,
        'primary_key': [
            'material',
            'location',
            'advance_days',
        ],
        'fields': [
            {
                'local_name': 'material',
                'db_name': 'material',
                'local_order': 1,
                'db_order': 1,
                'pandas_type': 'int64',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': 'M',
                'comment': '物料号',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'location',
                'db_name': 'location',
                'local_order': 2,
                'db_order': 2,
                'pandas_type': 'str',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': 'L',
                'comment': '地点',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'advance_days',
                'db_name': 'advance_days',
                'range': (0, None),
                'local_order': 3,
                'db_order': 3,
                'pandas_type': 'int64',
                'db_type': 'bigint',
                'primary_key': True,
                'notnull': True,
                'default': 99,
                'comment': '提前期',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'ao_percent',
                'db_name': 'ao_percent',
                'range': (0, 1),
                'local_order': 4,
                'db_order': 4,
                'pandas_type': 'float64',
                'db_type': 'double precision',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': 'AO比例',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
        ],
        'system_fields': [
            {
                'db_name': 'config_name',
                'db_order': 5,
                'db_type': 'str',
                'comment': '配置名',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
            {
                'db_name': 'db_write_time',
                'db_order': 7,
                'db_type': 'timestamp without time zone',
                'comment': '写库时间',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
        ],
    },
    'M1_DPSConfig': {
        'local_sheet': 'M1_DPSConfig',
        'data_source': None,
        'source_file': None,
        'db_table': 'cfg_m1_dpsconfig',
        'import_enabled': True,
        'primary_key': [
            'material',
            'location',
            'dps_location',
        ],
        'fields': [
            {
                'local_name': 'material',
                'db_name': 'material',
                'local_order': 1,
                'db_order': 1,
                'pandas_type': 'int64',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '物料',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'location',
                'db_name': 'location',
                'local_order': 2,
                'db_order': 2,
                'pandas_type': 'str',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '地点',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'dps_location',
                'db_name': 'dps_location',
                'local_order': 3,
                'db_order': 3,
                'pandas_type': 'str',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '工厂',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'dps_percent',
                'db_name': 'dps_percent',
                'range': (0, 1),
                'local_order': 4,
                'db_order': 4,
                'pandas_type': 'float64',
                'db_type': 'double precision',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': 'DPS地点分配比例',
                'comment_source': 'manual_mapping_completion',
                'db_field_exists': '是',
            },
        ],
        'system_fields': [
            {
                'db_name': 'config_name',
                'db_order': 5,
                'db_type': 'str',
                'comment': '配置名',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
            {
                'db_name': 'db_write_time',
                'db_order': 7,
                'db_type': 'timestamp without time zone',
                'comment': '写库时间',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
        ],
    },
    'M1_SupplyChoiceConfig': {
        'local_sheet': 'M1_SupplyChoiceConfig',
        'data_source': None,
        'source_file': None,
        'db_table': 'cfg_m1_supplychoiceconfig',
        'import_enabled': True,
        'primary_key': [
            'material',
            'location',
            'week',
        ],
        'fields': [
            {
                'local_name': 'material',
                'db_name': 'material',
                'local_order': 1,
                'db_order': 1,
                'pandas_type': 'object',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': 'M',
                'comment': '物料号',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'location',
                'db_name': 'location',
                'local_order': 2,
                'db_order': 2,
                'pandas_type': 'object',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': 'L',
                'comment': '地点',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'week',
                'db_name': 'week',
                'local_order': 3,
                'db_order': 3,
                'pandas_type': 'object',
                'db_type': 'bigint',
                'primary_key': True,
                'notnull': True,
                'default': 99,
                'comment': '仿真周',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'adjust_quantity',
                'db_name': 'adjust_quantity',
                'local_order': 4,
                'db_order': 4,
                'pandas_type': 'object',
                'db_type': 'double precision',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': '调整数量',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
        ],
        'system_fields': [
            {
                'db_name': 'config_name',
                'db_order': 5,
                'db_type': 'str',
                'comment': '配置名',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
            {
                'db_name': 'db_write_time',
                'db_order': 7,
                'db_type': 'timestamp without time zone',
                'comment': '写库时间',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
        ],
    },
    'M3_SafetyStock': {
        'local_sheet': 'M3_SafetyStock',
        'data_source': None,
        'source_file': None,
        'db_table': 'cfg_m3_safetystock',
        'import_enabled': True,
        'primary_key': [
            'material',
            'location',
            'date',
        ],
        'fields': [
            {
                'local_name': 'material',
                'db_name': 'material',
                'local_order': 1,
                'db_order': 1,
                'pandas_type': 'int64',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '物料号',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'location',
                'db_name': 'location',
                'local_order': 2,
                'db_order': 2,
                'pandas_type': 'str',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '地点',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'date',
                'db_name': 'date',
                'local_order': 3,
                'db_order': 3,
                'pandas_type': 'str',
                'db_type': 'timestamp without time zone',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '时间',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'safety_stock_qty',
                'db_name': 'safety_stock_qty',
                'range': (0, None),
                'local_order': 5,
                'db_order': 5,
                'pandas_type': 'float64',
                'db_type': 'double precision',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': '安全库存数量',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
        ],
        'system_fields': [
            {
                'db_name': 'config_name',
                'db_order': 6,
                'db_type': 'str',
                'comment': '配置名',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
            {
                'db_name': 'db_write_time',
                'db_order': 8,
                'db_type': 'timestamp without time zone',
                'comment': '写库时间',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
        ],
    },
    'M4_MaterialLocationLineCfg': {
        'local_sheet': 'M4_MaterialLocationLineCfg',
        'data_source': None,
        'source_file': None,
        'db_table': 'cfg_m4_materiallocationlinecfg',
        'import_enabled': True,
        'primary_key': [
            'material',
            'location',
            'delegate_line',
        ],
        'fields': [
            {
                'local_name': 'material',
                'db_name': 'material',
                'local_order': 1,
                'db_order': 1,
                'pandas_type': 'int64',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '物料号',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'location',
                'db_name': 'location',
                'local_order': 2,
                'db_order': 2,
                'pandas_type': 'str',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '地点',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'delegate_line',
                'db_name': 'delegate_line',
                'local_order': 3,
                'db_order': 3,
                'pandas_type': 'str',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '产线',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'prd_rate',
                'db_name': 'prd_rate',
                'range': (0, None),
                'local_order': 4,
                'db_order': 4,
                'pandas_type': 'int64',
                'db_type': 'double precision',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': '线速',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'min_batch',
                'db_name': 'min_batch',
                'range': (0, None),
                'local_order': 5,
                'db_order': 5,
                'pandas_type': 'int64',
                'db_type': 'double precision',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': '最少生产批量',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'rv',
                'db_name': 'rv',
                'range': (0, None),
                'local_order': 6,
                'db_order': 6,
                'pandas_type': 'int64',
                'db_type': 'double precision',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': 'rounding value',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'ptf',
                'db_name': 'ptf',
                'range': (0, None),
                'local_order': 7,
                'db_order': 7,
                'pandas_type': 'int64',
                'db_type': 'int',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': 'planning time fence',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'lsk',
                'db_name': 'lsk',
                'range': (0, None),
                'local_order': 8,
                'db_order': 8,
                'pandas_type': 'int64',
                'db_type': 'int',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': 'lot size key',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'day',
                'db_name': 'day',
                'range': (0, None),
                'local_order': 9,
                'db_order': 9,
                'pandas_type': 'int64',
                'db_type': 'bigint',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': 'day',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'MCT',
                'db_name': 'mct',
                'range': (0, None),
                'local_order': 10,
                'db_order': 10,
                'pandas_type': 'int64',
                'db_type': 'int',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': '微检时间',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
        ],
        'system_fields': [
            {
                'db_name': 'config_name',
                'db_order': 11,
                'db_type': 'str',
                'comment': '配置名',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
            {
                'db_name': 'db_write_time',
                'db_order': 13,
                'db_type': 'timestamp without time zone',
                'comment': '写库时间',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
        ],
    },
    'M4_LineCapacity': {
        'local_sheet': 'M4_LineCapacity',
        'data_source': None,
        'source_file': None,
        'db_table': 'cfg_m4_linecapacity',
        'import_enabled': True,
        'primary_key': [
            'location',
            'line',
            'date',
        ],
        'fields': [
            {
                'local_name': 'location',
                'db_name': 'location',
                'local_order': 1,
                'db_order': 1,
                'pandas_type': 'str',
                'db_type': 'str',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': '地点',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'line',
                'db_name': 'line',
                'local_order': 2,
                'db_order': 2,
                'pandas_type': 'str',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '生产线',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'date',
                'db_name': 'date',
                'local_order': 3,
                'db_order': 3,
                'pandas_type': 'datetime64[us]',
                'db_type': 'timestamp without time zone',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '日期',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'capacity',
                'db_name': 'capacity',
                'range': (0, None),
                'local_order': 4,
                'db_order': 4,
                'pandas_type': 'int64',
                'db_type': 'double precision',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': '可用产能小时',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
        ],
        'system_fields': [
            {
                'db_name': 'config_name',
                'db_order': 5,
                'db_type': 'str',
                'comment': '配置名',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
            {
                'db_name': 'db_write_time',
                'db_order': 7,
                'db_type': 'timestamp without time zone',
                'comment': '写库时间',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
        ],
    },
    'M4_ChangeoverMatrix': {
        'local_sheet': 'M4_ChangeoverMatrix',
        'data_source': None,
        'source_file': None,
        'db_table': 'cfg_m4_changeovermatrix',
        'import_enabled': True,
        'primary_key': [
            'from_material',
            'to_material',
        ],
        'fields': [
            {
                'local_name': 'from_material',
                'db_name': 'from_material',
                'local_order': 1,
                'db_order': 1,
                'pandas_type': 'int64',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '起始物料',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'to_material',
                'db_name': 'to_material',
                'local_order': 2,
                'db_order': 2,
                'pandas_type': 'int64',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '切换物料',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'changeover_id',
                'db_name': 'changeover_id',
                'local_order': 3,
                'db_order': 3,
                'pandas_type': 'str',
                'db_type': 'str',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': '转产类型',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
        ],
        'system_fields': [
            {
                'db_name': 'config_name',
                'db_order': 6,
                'db_type': 'str',
                'comment': '配置名',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
            {
                'db_name': 'db_write_time',
                'db_order': 8,
                'db_type': 'timestamp without time zone',
                'comment': '写库时间',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
        ],
    },
    'M4_ChangeoverDefinition': {
        'local_sheet': 'M4_ChangeoverDefinition',
        'data_source': None,
        'source_file': None,
        'db_table': 'cfg_m4_changeoverdefinition',
        'import_enabled': True,
        'primary_key': [
            'changeover_id',
            'line',
        ],
        'fields': [
            {
                'local_name': 'changeover_id',
                'db_name': 'changeover_id',
                'local_order': 1,
                'db_order': 1,
                'pandas_type': 'str',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '转产类型',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'line',
                'db_name': 'line',
                'local_order': 2,
                'db_order': 2,
                'pandas_type': 'str',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '生产线',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'time',
                'db_name': 'time',
                'range': (0, None),
                'local_order': 3,
                'db_order': 3,
                'pandas_type': 'float64',
                'db_type': 'double precision',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': '转产时间',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'cost',
                'db_name': 'cost',
                'range': (0, None),
                'local_order': 4,
                'db_order': 4,
                'pandas_type': 'int64',
                'db_type': 'double precision',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': '转产成本',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'mu_loss',
                'db_name': 'mu_loss',
                'range': (0, None),
                'local_order': 5,
                'db_order': 5,
                'pandas_type': 'float64',
                'db_type': 'double precision',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': '转产材料损失',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
        ],
        'system_fields': [
            {
                'db_name': 'config_name',
                'db_order': 6,
                'db_type': 'str',
                'comment': '配置名',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
            {
                'db_name': 'db_write_time',
                'db_order': 8,
                'db_type': 'timestamp without time zone',
                'comment': '写库时间',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
        ],
    },
    'M4_ProductionReliability': {
        'local_sheet': 'M4_ProductionReliability',
        'data_source': None,
        'source_file': None,
        'db_table': 'cfg_m4_productionreliability',
        'import_enabled': True,
        'primary_key': [
            'location',
            'line',
        ],
        'fields': [
            {
                'local_name': 'location',
                'db_name': 'location',
                'local_order': 1,
                'db_order': 1,
                'pandas_type': 'str',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '地点',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'line',
                'db_name': 'line',
                'local_order': 2,
                'db_order': 2,
                'pandas_type': 'str',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '产线',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
            {
                'local_name': 'pr',
                'db_name': 'pr',
                'range': (0, 1),
                'local_order': 3,
                'db_order': 3,
                'pandas_type': 'float64',
                'db_type': 'double precision',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': 'PR',
                'comment_source': 'description',
                'db_field_exists': '是',
            },
        ],
        'system_fields': [
            {
                'db_name': 'config_name',
                'db_order': 4,
                'db_type': 'str',
                'comment': '配置名',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
            {
                'db_name': 'db_write_time',
                'db_order': 6,
                'db_type': 'timestamp without time zone',
                'comment': '写库时间',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
        ],
    },
    'M5_PushPullModel': {
        'local_sheet': 'M5_PushPullModel',
        'data_source': None,
        'source_file': None,
        'db_table': 'cfg_m5_pushpullmodel',
        'import_enabled': True,
        'primary_key': [
            'material',
            'sending',
        ],
        'fields': [
            {
                'local_name': 'material',
                'db_name': 'material',
                'local_order': 1,
                'db_order': 1,
                'pandas_type': 'int64',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '物料号',
                'comment_source': 'manual_mapping_completion',
                'db_field_exists': '是',
            },
            {
                'local_name': 'sending',
                'db_name': 'sending',
                'local_order': 2,
                'db_order': 2,
                'pandas_type': 'str',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '发货点',
                'comment_source': 'manual_mapping_completion',
                'db_field_exists': '是',
            },
            {
                'local_name': 'model',
                'db_name': 'model',
                'enumerate': ['push', 'soft push'],
                'local_order': 3,
                'db_order': 3,
                'pandas_type': 'str',
                'db_type': 'str',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': 'push/pull/soft push策略模式',
                'comment_source': 'manual_mapping_completion',
                'db_field_exists': '是',
            },
        ],
        'system_fields': [
            {
                'db_name': 'config_name',
                'db_order': 4,
                'db_type': 'str',
                'comment': '配置名',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
            {
                'db_name': 'db_write_time',
                'db_order': 6,
                'db_type': 'timestamp without time zone',
                'comment': '写库时间',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
        ],
    },
    'M5_DeployConfig': {
        'local_sheet': 'M5_DeployConfig',
        'data_source': None,
        'source_file': None,
        'db_table': 'cfg_m5_deployconfig',
        'import_enabled': True,
        'primary_key': [
            'material',
            'sending',
            'receiving',
        ],
        'fields': [
            {
                'local_name': 'material',
                'db_name': 'material',
                'local_order': 1,
                'db_order': 1,
                'pandas_type': 'int64',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '物料号',
                'comment_source': 'manual_mapping_completion',
                'db_field_exists': '是',
            },
            {
                'local_name': 'sending',
                'db_name': 'sending',
                'local_order': 2,
                'db_order': 2,
                'pandas_type': 'str',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '发货点',
                'comment_source': 'manual_mapping_completion',
                'db_field_exists': '是',
            },
            {
                'local_name': 'receiving',
                'db_name': 'receiving',
                'local_order': 3,
                'db_order': 3,
                'pandas_type': 'str',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '收货点',
                'comment_source': 'manual_mapping_completion',
                'db_field_exists': '是',
            },
            {
                'local_name': 'moq',
                'db_name': 'moq',
                'range': (0, None),
                'local_order': 4,
                'db_order': 4,
                'pandas_type': 'int64',
                'db_type': 'double precision',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': '最小起订量',
                'comment_source': 'manual_mapping_completion',
                'db_field_exists': '是',
            },
            {
                'local_name': 'rv',
                'db_name': 'rv',
                'range': (0, None),
                'local_order': 5,
                'db_order': 5,
                'pandas_type': 'int64',
                'db_type': 'double precision',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': '四舍五入值',
                'comment_source': 'manual_mapping_completion',
                'db_field_exists': '是',
            },
            {
                'local_name': 'lsk',
                'db_name': 'lsk',
                'range': (0, None),
                'local_order': 6,
                'db_order': 6,
                'pandas_type': 'int64',
                'db_type': 'int',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': '批量规模键',
                'comment_source': 'manual_mapping_completion',
                'db_field_exists': '是',
            },
            {
                'local_name': 'day',
                'db_name': 'day',
                'range': (0, None),
                'local_order': 7,
                'db_order': 7,
                'pandas_type': 'int64',
                'db_type': 'bigint',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': '部署配置天数参数',
                'comment_source': 'manual_mapping_completion',
                'db_field_exists': '是',
            },
        ],
        'system_fields': [
            {
                'db_name': 'config_name',
                'db_order': 8,
                'db_type': 'str',
                'comment': '配置名',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
            {
                'db_name': 'db_write_time',
                'db_order': 10,
                'db_type': 'timestamp without time zone',
                'comment': '写库时间',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
        ],
    },
    'M6_TruckReleaseCon': {
        'local_sheet': 'M6_TruckReleaseCon',
        'data_source': None,
        'source_file': None,
        'db_table': 'cfg_m6_truckreleasecon',
        'import_enabled': True,
        'primary_key': [
            'sending',
            'receiving',
            'truck_type',
        ],
        'fields': [
            {
                'local_name': 'sending',
                'db_name': 'sending',
                'local_order': 1,
                'db_order': 1,
                'pandas_type': 'str',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '发货点',
                'comment_source': 'manual_mapping_completion',
                'db_field_exists': '是',
            },
            {
                'local_name': 'receiving',
                'db_name': 'receiving',
                'local_order': 2,
                'db_order': 2,
                'pandas_type': 'str',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '收货点',
                'comment_source': 'manual_mapping_completion',
                'db_field_exists': '是',
            },
            {
                'local_name': 'truck_type',
                'db_name': 'truck_type',
                'local_order': 3,
                'db_order': 3,
                'pandas_type': 'str',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '车型',
                'comment_source': 'manual_mapping_completion',
                'db_field_exists': '是',
            },
            {
                'local_name': 'optimal_type',
                'db_name': 'optimal_type',
                'local_order': 4,
                'db_order': 4,
                'pandas_type': 'float64',
                'db_type': 'str',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': '装车优化类型',
                'comment_source': 'manual_mapping_completion',
                'db_field_exists': '是',
            },
            {
                'local_name': 'WFR',
                'db_name': 'wfr',
                'local_order': 5,
                'db_order': 5,
                'pandas_type': 'int64',
                'db_type': 'double precision',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': '重量装载率阈值',
                'comment_source': 'manual_mapping_completion',
                'db_field_exists': '是',
            },
            {
                'local_name': 'VFR',
                'db_name': 'vfr',
                'local_order': 6,
                'db_order': 6,
                'pandas_type': 'float64',
                'db_type': 'double precision',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': '体积装载率阈值',
                'comment_source': 'manual_mapping_completion',
                'db_field_exists': '是',
            },
            {
                'local_name': 'MDQ',
                'db_name': 'mdq',
                'range': (0, None),
                'local_order': 7,
                'db_order': 7,
                'pandas_type': 'int64',
                'db_type': 'double precision',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': '最小发运数量阈值',
                'comment_source': 'manual_mapping_completion',
                'db_field_exists': '是',
            },
        ],
        'system_fields': [
            {
                'db_name': 'config_name',
                'db_order': 8,
                'db_type': 'str',
                'comment': '配置名',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
            {
                'db_name': 'db_write_time',
                'db_order': 10,
                'db_type': 'timestamp without time zone',
                'comment': '写库时间',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
        ],
    },
    'M6_MaterialMD': {
        'local_sheet': 'M6_MaterialMD',
        'data_source': None,
        'source_file': None,
        'db_table': 'cfg_m6_materialmd',
        'import_enabled': True,
        'primary_key': [
            'material',
        ],
        'fields': [
            {
                'local_name': 'material',
                'db_name': 'material',
                'local_order': 1,
                'db_order': 1,
                'pandas_type': 'int64',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '物料号',
                'comment_source': 'manual_mapping_completion',
                'db_field_exists': '是',
            },
            {
                'local_name': 'demand_unit_to_weight',
                'db_name': 'demand_unit_to_weight',
                'range': (0, None),
                'local_order': 5,
                'db_order': 5,
                'pandas_type': 'float64',
                'db_type': 'double precision',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': '需求单位到重量的换算系数',
                'comment_source': 'manual_mapping_completion',
                'db_field_exists': '是',
            },
            {
                'local_name': 'demand_unit_to_volume',
                'db_name': 'demand_unit_to_volume',
                'range': (0, None),
                'local_order': 6,
                'db_order': 6,
                'pandas_type': 'float64',
                'db_type': 'double precision',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': '需求单位到体积的换算系数',
                'comment_source': 'manual_mapping_completion',
                'db_field_exists': '是',
            },
        ],
        'system_fields': [
            {
                'db_name': 'config_name',
                'db_order': 8,
                'db_type': 'str',
                'comment': '配置名',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
            {
                'db_name': 'db_write_time',
                'db_order': 10,
                'db_type': 'timestamp without time zone',
                'comment': '写库时间',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
        ],
    },
    'M6_DeliveryDelayDistribution': {
        'local_sheet': 'M6_DeliveryDelayDistribution',
        'data_source': None,
        'source_file': None,
        'db_table': 'cfg_m6_deliverydelaydistribution',
        'import_enabled': True,
        'primary_key': [
            'date',
            'sending',
            'receiving',
            'delay_days',
        ],
        'fields': [
            {
                'local_name': 'date',
                'db_name': 'date',
                'local_order': 1,
                'db_order': 1,
                'pandas_type': 'str',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '日期',
                'comment_source': 'manual_mapping_completion',
                'db_field_exists': '是',
            },
            {
                'local_name': 'sending',
                'db_name': 'sending',
                'local_order': 2,
                'db_order': 2,
                'pandas_type': 'str',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '发货点',
                'comment_source': 'manual_mapping_completion',
                'db_field_exists': '是',
            },
            {
                'local_name': 'receiving',
                'db_name': 'receiving',
                'local_order': 3,
                'db_order': 3,
                'pandas_type': 'str',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '收货点',
                'comment_source': 'manual_mapping_completion',
                'db_field_exists': '是',
            },
            {
                'local_name': 'delay_days',
                'db_name': 'delay_days',
                'range': (0, None),
                'local_order': 4,
                'db_order': 4,
                'pandas_type': 'int64',
                'db_type': 'bigint',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '运输延迟天数',
                'comment_source': 'manual_mapping_completion',
                'db_field_exists': '是',
            },
            {
                'local_name': 'probability',
                'db_name': 'probability',
                'range': (0, 1),
                'local_order': 5,
                'db_order': 5,
                'pandas_type': 'float64',
                'db_type': 'double precision',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': '运输延迟概率',
                'comment_source': 'manual_mapping_completion',
                'db_field_exists': '是',
            },
        ],
        'system_fields': [
            {
                'db_name': 'config_name',
                'db_order': 6,
                'db_type': 'str',
                'comment': '配置名',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
            {
                'db_name': 'db_write_time',
                'db_order': 8,
                'db_type': 'timestamp without time zone',
                'comment': '写库时间',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
        ],
    },
    'M6_MDQBypassRules': {
        'local_sheet': 'M6_MDQBypassRules',
        'data_source': None,
        'source_file': None,
        'db_table': 'cfg_m6_mdqbypassrules',
        'import_enabled': True,
        'primary_key': [
            'sending',
            'receiving',
            'truck_type',
            'demand_element',
        ],
        'fields': [
            {
                'local_name': 'sending',
                'db_name': 'sending',
                'local_order': 1,
                'db_order': 1,
                'pandas_type': 'str',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '发货点',
                'comment_source': 'manual_mapping_completion',
                'db_field_exists': '是',
            },
            {
                'local_name': 'receiving',
                'db_name': 'receiving',
                'local_order': 2,
                'db_order': 2,
                'pandas_type': 'str',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '收货点',
                'comment_source': 'manual_mapping_completion',
                'db_field_exists': '是',
            },
            {
                'local_name': 'truck_type',
                'db_name': 'truck_type',
                'local_order': 3,
                'db_order': 3,
                'pandas_type': 'str',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '车型',
                'comment_source': 'manual_mapping_completion',
                'db_field_exists': '是',
            },
            {
                'local_name': 'demand_element',
                'db_name': 'demand_element',
                'local_order': 4,
                'db_order': 4,
                'pandas_type': 'str',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '需求类型',
                'comment_source': 'manual_mapping_completion',
                'db_field_exists': '是',
            },
            {
                'local_name': 'condition_logic',
                'db_name': 'condition_logic',
                'local_order': 5,
                'db_order': 5,
                'pandas_type': 'str',
                'db_type': 'str',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': 'MDQ绕过规则条件逻辑',
                'comment_source': 'manual_mapping_completion',
                'db_field_exists': '是',
            },
            {
                'local_name': 'rule_id',
                'db_name': 'rule_id',
                'local_order': 6,
                'db_order': 6,
                'pandas_type': 'str',
                'db_type': 'str',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': '规则ID',
                'comment_source': 'manual_mapping_completion',
                'db_field_exists': '是',
            },
        ],
        'system_fields': [
            {
                'db_name': 'config_name',
                'db_order': 7,
                'db_type': 'str',
                'comment': '配置名',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
            {
                'db_name': 'db_write_time',
                'db_order': 9,
                'db_type': 'timestamp without time zone',
                'comment': '写库时间',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
        ],
    },
    'M6_TruckTypeSpecs': {
        'local_sheet': 'M6_TruckTypeSpecs',
        'data_source': None,
        'source_file': None,
        'db_table': 'cfg_m6_trucktypespecs',
        'import_enabled': True,
        'primary_key': [
            'truck_type',
        ],
        'fields': [
            {
                'local_name': 'truck_type',
                'db_name': 'truck_type',
                'local_order': 1,
                'db_order': 1,
                'pandas_type': 'str',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': None,
                'comment': '车型',
                'comment_source': 'manual_mapping_completion',
                'db_field_exists': '是',
            },
            {
                'local_name': 'capacity_qty_in_weight',
                'db_name': 'capacity_qty_in_weight',
                'range': (0, None),
                'local_order': 4,
                'db_order': 4,
                'pandas_type': 'int64',
                'db_type': 'double precision',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': '车型重量容量',
                'comment_source': 'manual_mapping_completion',
                'db_field_exists': '是',
            },
            {
                'local_name': 'capacity_qty_in_volume',
                'db_name': 'capacity_qty_in_volume',
                'range': (0, None),
                'local_order': 5,
                'db_order': 5,
                'pandas_type': 'int64',
                'db_type': 'double precision',
                'primary_key': False,
                'notnull': True,
                'default': None,
                'comment': '车型体积容量',
                'comment_source': 'manual_mapping_completion',
                'db_field_exists': '是',
            },
        ],
        'system_fields': [
            {
                'db_name': 'config_name',
                'db_order': 6,
                'db_type': 'str',
                'comment': '配置名',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
            {
                'db_name': 'db_write_time',
                'db_order': 8,
                'db_type': 'timestamp without time zone',
                'comment': '写库时间',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
        ],
    },
    'M6_TruckCapacityPlan': {
        'local_sheet': 'M6_TruckCapacityPlan',
        'data_source': None,
        'source_file': None,
        'db_table': 'cfg_m6_truckcapacityplan',
        'import_enabled': True,
        'primary_key': [
            'date',
            'sending',
            'receiving',
            'truck_type',
        ],
        'fields': [
            {
                'local_name': 'date',
                'db_name': 'date',
                'local_order': 1,
                'db_order': 1,
                'pandas_type': 'object',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': '1942-01-01T00:00:00',
                'comment': '日期',
                'comment_source': 'manual_mapping_completion',
                'db_field_exists': '是',
            },
            {
                'local_name': 'sending',
                'db_name': 'sending',
                'local_order': 2,
                'db_order': 2,
                'pandas_type': 'object',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': 'S',
                'comment': '发货点',
                'comment_source': 'manual_mapping_completion',
                'db_field_exists': '是',
            },
            {
                'local_name': 'receiving',
                'db_name': 'receiving',
                'local_order': 3,
                'db_order': 3,
                'pandas_type': 'object',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': 'R',
                'comment': '收货点',
                'comment_source': 'manual_mapping_completion',
                'db_field_exists': '是',
            },
            {
                'local_name': 'truck_type',
                'db_name': 'truck_type',
                'local_order': 4,
                'db_order': 4,
                'pandas_type': 'object',
                'db_type': 'str',
                'primary_key': True,
                'notnull': True,
                'default': 'T',
                'comment': '车型',
                'comment_source': 'manual_mapping_completion',
                'db_field_exists': '是',
            },
            {
                'local_name': 'truck_number',
                'db_name': 'truck_number',
                'range': (0, None),
                'local_order': 5,
                'db_order': 5,
                'pandas_type': 'object',
                'db_type': 'int',
                'primary_key': False,
                'notnull': True,
                'default': 999,
                'comment': '可用车辆数量',
                'comment_source': 'manual_mapping_completion',
                'db_field_exists': '是',
            },
        ],
        'system_fields': [
            {
                'db_name': 'config_name',
                'db_order': 6,
                'db_type': 'str',
                'comment': '配置名',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
            {
                'db_name': 'db_write_time',
                'db_order': 8,
                'db_type': 'timestamp without time zone',
                'comment': '写库时间',
                'comment_source': 'remark',
                'db_field_exists': '是',
            },
        ],
    },
}


def get_config_table_schemas() -> dict[str, dict[str, Any]]:
    """返回以 Sheet key 为索引的配置表 schema 深拷贝。"""
    return deepcopy(CONFIG_TABLE_SCHEMAS)


def get_config_table_mapping() -> dict[str, Any]:
    """返回配置表导入与质量检测使用的完整 schema 映射。"""
    return {
        "version": 1,
        "mapping_source": deepcopy(CONFIG_SCHEMA_SOURCE),
        "scope": deepcopy(CONFIG_SCOPE),
        "system_field_policy": deepcopy(SYSTEM_FIELD_POLICY),
        "tables": get_config_table_schemas(),
    }


def get_config_table_schema_by_sheet(sheet_name: str) -> dict[str, Any] | None:
    """按本地 Sheet 名查找并返回单张配置表 schema 深拷贝。"""
    target = str(sheet_name)
    for key, table_cfg in CONFIG_TABLE_SCHEMAS.items():
        if str(table_cfg.get("local_sheet") or key) == target:
            return deepcopy(table_cfg)
    return None


__all__ = [
    "CONFIG_SCHEMA_SOURCE",
    "CONFIG_SCOPE",
    "SYSTEM_FIELD_POLICY",
    "CONFIG_TABLE_SCHEMAS",
    "get_config_table_mapping",
    "get_config_table_schema_by_sheet",
    "get_config_table_schemas",
]
